version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.4
    steps:
      - checkout
      - run:
          name: Install Ruby Dependencies
          command: bundle install
      - run:
          name: Run specs
          command: bundle exec rspec --color --format progress spec
      - run:
          name: Run features
          command: bundle exec cucumber
      - run:
          name: Release gem
          command: ./script/publish
