#!/usr/bin/env sh

echo
echo ' *** Running tests...'
bundle exec rake

if [ $? != 0 ]
then
    echo
    echo ' *** Test status: FAILED'
    echo ' *** Exiting... Please fix the tests then release the module again.'
    exit -1
else
    echo
    echo ' *** Test status: SUCCESS'
fi

if [ $# == 1 ]
then
    VERSION=$1
else
    VERSION='patch'
fi

echo
echo " *** Bumping version... $VERSION"
gem bump -v $VERSION --no-commit

VERSION=`ruby -r ./lib/zuppler/version.rb -e 'puts Zuppler::VERSION'`

echo
echo " *** Commit release changes ... $VERSION"
bundle install
git add .
git commit -m "Release $VERSION"
git push
